config/routes.rb
Nyyttarit::Application.routes.draw do
  resources :items
  resources :events
  

  root :to => "events#home"
  
  match "resources/js/main/:app" => "events#mainjs"
  match "resources/templates/:tmplname" => "events#template"
  match "events/new/:item_count" => "events#new"
  
  match "events/:id/simple" => "events#show_simple"
  
  match "events/:id/:hash" => "events#edit"
  
  match "events/add-attendant" => "events#add_attendant"
  match "events/:id/add-attendant" => "events#add_attendant"
  

end

app/models/attendant.rb
# == Schema Information
#
# Table name: attendants
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  event_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Attendant < ActiveRecord::Base
  belongs_to :event
  has_many :brought_items, :dependent => :destroy
  attr_accessible :name
  validates :name,  :presence => true,
                    :length => { :maximum => 50 }
  validates_associated :brought_items                 
end

app/models/brought_item.rb
# == Schema Information
#
# Table name: brought_items
#
#  id           :integer         not null, primary key
#  quantity     :integer
#  comment      :string(255)
#  attendant_id :integer
#  item_id      :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class BroughtItem < ActiveRecord::Base
  #TODO Add before callback to check the quantity
  belongs_to :attendant
  belongs_to :item
  attr_accessible :comment, :quantity, :item_id
  validates :comment, :length => { :maximum => 255 }
  validates :quantity, :presence => true,
                       :numericality => { :only_integer => true, :greater_than => 0 }
  validate :quantity_cannot_be_greater_than_current_quantity                   
  
  def quantity_cannot_be_greater_than_current_quantity
    item = Item.find(self.item_id)
    if self.quantity > item.needed_quantity
      errors.add(:quantity, "Quantity can't be greater than the required amount.")
    end
  end  
                      
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  description       :string(255)
#  email             :string(255)
#  hash_val          :string(255)     default("0")
#  own_items_allowed :boolean
#  created_at        :datetime
#  updated_at        :datetime
#

class Event < ActiveRecord::Base
  before_create :set_id, :set_hash
  has_many :items, :dependent => :destroy
  has_many :attendants, :dependent => :destroy
  has_many :brought_items, :through => :attendants
  attr_accessible :id, :name, :description, :email, :items, :items_attributes, :hash_val, :own_items_allowed
  accepts_nested_attributes_for :items, :allow_destroy => true
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => { :message => "The event should have a name." },
                    :length => { :maximum => 50, :message => "The name of the event should be less than 50 characters."}
  validates :email, :presence => { :message => "The e-mail adress is required." },
                    :format   => { :with => email_regex, :message => "The e-mail adress should be form example@mail.com." },
                    :length => { :maximum => 255 }
  validates :description, :length => { :maximum => 255, :message => "The length of the description should be less than 255 characters." }
                              
  validates_associated :items, :attendants, :brought_items                  
  private 
  
  #Sets 8-digit random integer for primary key
  def set_id
    self.id = Array.new(8){rand(9)}.join
  end
  
  def set_hash
    self.hash_val = Array.new(8){rand(9)}.join
  end
  
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id               :integer         not null, primary key
#  name             :string(255)
#  needed_quantity  :integer
#  current_quantity :integer         default(0)
#  event_id         :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class Item < ActiveRecord::Base
  belongs_to :event
  has_many :brought_items
  attr_accessor :item_id
  attr_accessible :name, :needed_quantity, :current_quantity
  
  validates :name,  :presence => { :message => "The item should have a name." },
                    :length => { :maximum => 50, :message => "The name of the item should be less than 50 characters." }
  validates :needed_quantity, :presence => true,
                              :numericality => { :only_integer => true, :greater_than => 0, 
                                                  :message => "Minimum quantity for items is 1." }                                                   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  # GET /events
  # def index
  #  @events = Event.all
  # end

  # GET /events/1
  def show
    @event = Event.find(params[:id])
    @items = @event.items
    @title = @event.name
    @main_app = '/resources/js/main/event'
  end
  
  # For a non-javascript version of the show view.
  def show_simple
    @event = Event.find(params[:id])
    @items = @event.items
    @title = @event.name
    render :action => "show"
  end
  
  def show_urls
    @event = Event.find(params[:id])
  end
  
  # GET /events/new
  def new
    @item_count = params[:item_count]?params[:item_count]:"1"
    @item_count = Integer(@item_count)
    @js = false
    @event = Event.new
    @title = "New event"
    for i in 1..@item_count
      @event.items.build
    end
  end
  
  # Helper method for adding a new item
  def add_item    
    @event.items.new
    render :action => "new"
  end
  
  def mainjs
    @app = params[:app]
    respond_to do |format|
      format.js
    end
  end
  
  # GET /
  def home
    @title = "Home"
    @js = true
    @event = Event.new
    @main_app = '/resources/js/main/home'
    @event.items.build
  end
  
  # GET /events/1312314/54325425
  def edit
    @event = Event.where("hash_val = ?", params[:hash]).first
    @main_app = '/resources/js/main/edit'
    @title = "Editing " + @event.name
  end

  
  # POST /events
  def create
    @event = Event.new(params[:event])
    
      if @event.save
        redirect_to(@event, :notice => "Notice")
      else
        @main_app = '/resources/js/main/home'
        @title = "Home"
        render :action => "home"
      end
  end

  # PUT /events/1
  def update
    @event = Event.find(params[:id])

      if @event.update_attributes(params[:event])
        redirect_to(@event, :notice => 'Event was successfully updated.')
      else
        render :action => "edit"
      end
  end

  # DELETE /events/1
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to(events_url)
  end
  
  # Adds a new attendant to event.
  def add_attendant
    @event = Event.find(params[:id])
    # If attendant already exists, items are added to him/her.
    if @event.attendants.exists?(:name => params[:name])
      @attendant = @event.attendants.where("name = ?", params[:name]).first
    else
      @attendant = @event.attendants.build(:name => params[:name])
    end
    # Process all chosen items.
    params[:items].each do |item|
      item = item[1]
      if (item['item-amount'] == "0")
        next
      end
      @bi = @attendant.brought_items.build(:item_id => item['item-id'], :quantity => item['item-amount'], :comment => item['item-comment'])
      @bi.item.current_quantity += @bi.quantity
      @bi.item.save
    end
    @attendant.save
    respond_to do |format|
      format.json { render :json => @event.brought_items }
      format.html { redirect_to @event }
    end
  end
  
  # For retrieving HTML templates for javascript
  def template
    @template_name = "_"+params[:tmplname]
    respond_to do |format|
      format.html { render @template_name, :layout => false }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/events/_checked_item.html.erb
<tr class="<%= even_row ? "row-even" : "row-odd" %> checked-item">
    <td class="item-name"><span><%= b_item.item.name %></span></td>
    <td class="item-amount"><span><%= b_item.quantity %></span></td>
    <td class="item-author"><span><%= b_item.attendant.name %></span></td>
    <td class="item-comment"><span><%= b_item.comment %></span></td>
</tr>

app/views/events/_footer.html.erb
<footer>
    
</footer>

app/views/events/_form.html.erb
<div id="eventCreationForm" <%= @js ? "class=hidden" : "" %>>
    <div id="eventCreationHeader">
        <h2><%= new_event ? "Create a new event" : "Editing event \"#{@event.name}\"" %></h2>
    </div>
    <%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
    <div id="errorExplanation" class="ui-state-error ui-corner-all">
        <h2>Note! <%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
        <ul>
            <% @event.errors.each do |attr, msg| %>
            <li>
                <%= msg %>
            </li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <div class="form-row">
        <h3>Event details</h3>
    </div>
    <div class="field form-row">
        <div class="label">
            <%= f.label :name, "Name your event" %>
        </div>
        <div class="inputgroup">
            <%= f.text_field :name %>
            <div class="hint">
              <div class="hint-button button ui-state-default ui-corner-all">
                <span class="ui-icon ui-icon-info"></span>
              </div>
              <div class="hint-message ui-state-highlight ui-corner-all">
                <span class="ui-icon ui-icon-triangle-1-w"></span>
                <span class="hint-text">Event name is something the event can be recognized with. It is visible in when viewing and editing your event.</span>
              </div>
            </div>
        </div>
    </div>
    <div class="field form-row textarea">
        <div class="label">
            <%= f.label :description, "Event description" %>
        </div>
        <div class="inputgroup">
            <%= f.text_area :description, :rows => "4"%>
            <div class="hint">
              <div class="hint-button button ui-state-default ui-corner-all">
                <span class="ui-icon ui-icon-info"></span>
              </div>
              <div class="hint-message ui-state-highlight ui-corner-all">
                <span class="ui-icon ui-icon-triangle-1-w"></span>
                <span class="hint-text">Enter a description of your event. The event description is a short story about why you need the items below. The description will be visible on the event page.</span>
              </div>
            </div>
        </div>
    </div>
    <div class="field form-row">
        <div class="label">
            <%= f.label :email, "Your email" %>
        </div>
        <div class="inputgroup">
            <%= f.text_field :email %>
            <div class="hint">
              <div class="hint-button button ui-state-default ui-corner-all">
                <span class="ui-icon ui-icon-info"></span>
              </div>
              <div class="hint-message ui-state-highlight ui-corner-all">
                <span class="ui-icon ui-icon-triangle-1-w"></span>
                <span class="hint-text">Your email is only used for sending you the links to view and edit your event. Your email address is <strong>never</strong> given to any third parties.</span>
              </div>
            </div>
        </div>
    </div>
    <div class="form-row">
        <h3>Items</h3>
    </div>
    <div id="items" class="form-row">
        <div class="label">
            <label>Which items are needed?</label>
        </div>
        <div class="inputgroup">
            <label>Give the name and quantity of each item.</label>
        </div>
    </div>
    <div id="itemList" class="form-row">
        <div class="inputgroup">
            <% f.fields_for :items do |builder| %>
              <%= render 'item_field', :f => builder %>
            <% end %>
        </div>
    </div>
    <div class="form-actions form-row">
      <a class="no-js-element" href="/events/new/<%= if new_event then item_count + 1 end %>">
        <div class="inputgroup">
            <span id="addNewItemButton" class="button ui-state-default ui-corner-all">Add another</span>
        </div>
      </a>
    </div>
    <div class="form-actions form-row">
        <%= f.submit new_event ? "Submit" : "Confirm", :class => "ui-state-default ui-corner-all submit button"%>
    </div>
    <% end %>
</div>

app/views/events/_header.html.erb
<header>
    <a href="/">
      <img src="/images/camilonalogo.png" alt="" width="100" height="33" />
    </a>
    <div class="menubuttons container">
        <div id="about" class="button">
            <span>About</span>
        </div>
        <div id="privacy" class="button">
            <span>Privacy</span>
        </div>
        <div id="feedback" class="button">
            <span>Feedback</span>
        </div>
    </div>
    <div id="dialog" style="display: none">
        
    </div>
</header>

app/views/events/_item_field.html.erb
<div class="item-field">
    <%= f.text_field :name, :placeholder => "Item name"%>
    <%= f.number_field :needed_quantity, :min => "1", :value => "1"%> 
    <div class="ui-state-default ui-corner-all remove-item button secondary">
        <span class="ui-icon ui-icon-closethick">Remove</span>
    </div>
</div>

app/views/events/_needed_item.html.erb
<% needed_quantity = item.needed_quantity - item.current_quantity %>
<% if needed_quantity > 0 %>
<div class="needed-item button visible">
    <span class="item-id hidden"><%= item.id %></span>
    <span class="name"><%= item.name %></span>
    <span class="needed-quantity"><%= needed_quantity %></span>
</div>
<% end %>

app/views/events/_user_item.html.erb
<% 
simpleversion = (defined? item_index) && (defined? item)
if (simpleversion)
  id = item.id
  name = item.name
  quantity = item.needed_quantity - item.current_quantity
  min = 0
  hash_name = "items[item"+item_index.to_s()+"]"
else
  id = ""
  name = "Item name"
  quantity = 1
  min = 1
  hash_name = "item"
end 
%>
<% if quantity > 0 %>
<div class="user-item">
    <% if simpleversion %>
      <span><%= quantity %></span>
    <% end %>
    <input type="hidden" name="<%= hash_name %>[item-id]" class="item-id" value="<%= id %>" />
    <span class="name"><%= name %></span>
    <input type="text" name="<%= hash_name %>[item-comment]" placeholder="Comment" class="comment"/>
    <input type="number" name="<%= hash_name %>[item-amount]" min="<%= min %>" max="<%= quantity %>" value="<%= min %>" class="amount"/>
    <% if !simpleversion %>
    <div class="ui-state-default ui-corner-all remove-item button secondary">
        <span class="ui-icon ui-icon-closethick"></span>
    </div>
    <% end %>
</div>
<% end %>

app/views/events/edit.html.erb
<div id="page" class="container" role="main">
    <div id="eventCreationContainer" class="container">
        <%= render 'form', :new_event => false, :item_count => 0 %>
    </div>
</div>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/home.html.erb
<div id="page" class="container" role="main">
  <div id="serviceLogo">
    <img src="/images/camilonalogo.png" alt="" width="300" height="100"/>
  </div>
  <div id="eventCreationContainer" class="container">
    <a class="no-js-element" href="/events/new">
    <div id="createAnEvent" class="ui-state-default button">
      <span id="createEventLabel">Create an event</span>
    </div> </a>
    <%= render 'form', :new_event => true, :item_count => 1 %>
  </div>
  <div id="presentationContainer" class="container content">
    <h3>The doodle of items.</h3>
    <div id="instructions">
   	 <img src="/images/instructions.png" alt="" width="903" height="329"/>
  	</div>
  </div>
  <div id="infoLinks" class="menubuttons">
        <div id="about" class="button">
            <span>About</span>
        </div>
        <div id="privacy" class="button">
            <span>Privacy</span>
        </div>
        <div id="feedback" class="button">
            <span>Feedback</span>
        </div>
    </div>
    <div id="dialog" style="display: none">
        
    </div>
</div>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Email</th>
    <th>Own items</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.description %></td>
    <td><%= event.email %></td>
    <td><%= event.own_items_allowed %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/mainjs.js.erb
require.config({
    baseUrl: '/javascripts',
  
    paths: {
        'jquery': 'libs/jquery-1.7.1.min',
        'jquery-ui': 'libs/jquery-ui-1.8.18.custom.min',
        'jquery-rails': 'libs/jquery-rails-module',
        'text': 'libs/text',
        'order': 'libs/order',
        'resources': '../resources'
    }
});

require([
    'order!jquery',
    'order!jquery-ui'
], function() {
  require([
    'views/<%= @app %>',
    'common'
    ], function(App, Common) {
    App.initialize();
    Common.initialize();
  });
});

app/views/events/new.html.erb
<div id="page" class="container" role="main">
    <div id="eventCreationContainer" class="container">
        <%= render 'form', :new_event => true, :item_count => @item_count %>
    </div>
</div>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% simple_version = controller.action_name == "show_simple" %>
<div id="page" class="container" role="main">
  <div id="eventInformation" class="section">
    <div id="eventAuthor">
      <h3>Event created by:</h3>
      <span><%= @event.email %></span>
    </div>
    <h2><%= @event.name %></h2>
    <p>
      <%= @event.description %>
    </p>
    <% if flash[:notice] %>
    <div id="eventLink">
      <p>
        <strong>Send this link to participants:</strong>
      </p>
      <div id="eventUrl" class="ui-state-highlight ui-corner-all">
        <%= link_to event_url(@event), @event %>
      </div>
      <div>
      <p>
        <strong>Save this link for editing the event:</strong>
      </p>
       <div id="eventUrl" class="ui-state-highlight ui-corner-all">
        <%= link_to event_url(@event) + "/" + @event.hash_val.to_s, event_url(@event) + "/" + @event.hash_val.to_s%>
      </div>
      <div>
      </div>
        <p>For a non-javascript version of this page, <%= link_to "click here", event_url(@event)+"/simple"%>.</p>
      </div>
    </div>
    <% end %>

  </div>
  <% if !simple_version %>
  <div id="eventItems" class="section">
    <h3>These items are still needed:</h3>
    <div id="eventItemPool" class="panel pool">
      <% @event.items.each do |item| %>
      <%= render 'needed_item', :item => item %>
      <% end %>
      <p class="emptiness-indicator <%= @event.items.count > 0 ? "hidden" : "" %>">
        OMG! There are no more items to bring.
      </p>
    </div>
  </div>
  <% end %>
  <% if simple_version %>
  <div id="eventItems" class="section">
    <h3>Select the items you want to bring</h3>
    <%= form_for(@event, :url => "/events/"+@event.id.to_s()+"/add-attendant") do |f| %>
    <div class="panel user-information">
      <% @event.items.each_with_index do |item, i| %>
      <%= render "user_item", :item => item, :item_index => i+1 %>
      <% end %>
      <input type="text" placeholder="Write your name here" name="name" />
      <div class="form-actions form-row">
        <%= f.submit "Confirm", :class => "ui-state-default ui-corner-all submit button"%>
      </div>
    </div>
    <% end %>
  </div>
  <% else %>
  <div id="eventUserActions" class="section">
    <h3>What are you bringing?</h3>
    <div>
      <form id="eventUserActionsForm">
        <input id="eventid" type="hidden" value="<%= @event.id %>" />
        <div id="userItems" class="panel user-information">
          <p class="emptiness-indicator">
            Click items in the above box to add them here.
          </p>
        </div>
        <input id="userName" type="text" placeholder="Write your name here" name="params[username]" />
        <div id="userItemConfirm" class="button ui-state-default ui-corner-all">
          <span>Confirm items</span>
        </div>
      </form>
    </div>
  </div>
  <% end %>
  <div id="checkedEventItems" class="section">
    <h3>These items are being brought by others:</h3>
    <div class="pool">
      <table id="checkedEventItemsPool" class="pool">
        <% if @event.attendants.count > 0 %>
        <tr class="header-row">
          <th><span>Item name</span></th>
          <th><span>Amount</span></th>
          <th><span>Who is bringing this item</span></th>
          <th><span>Comment</span></th>
        </tr>
        <% total_items = 0 %>
        <% @event.attendants.each do |attendant| %>
        <% attendant.brought_items.each do |item| %>
        <%= render 'checked_item', :b_item => item, :even_row => (total_items += 1) % 2 == 0 %>
        <% end %>
        <% end %>
        <% end %>
        <tr class="<%= @event.attendants.count > 0 ? "hidden" : "" %> emptiness-indicator row-odd">
          <td><span>No-one is bringing any items at the moment.</span></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/items/_footer.html.erb
<footer>
    <div class="menubuttons container">
        <div id="about" class="button">
            <span>About</span>
        </div>
        <div id="privacy" class="button">
            <span>Privacy</span>
        </div>
        <div id="feedback" class="button">
            <span>Feedback</span>
        </div>
    </div>
    <div id="dialog" style="display: none">
        
    </div>
</footer>

app/views/items/_header.html.erb
<header>
    Header content.
</header>

app/views/items/_item.html.erb
<tr>
  <td class="event">
    <span class="name"><%= item.name %></span>
    <span class="quantity"><%= item.needed_quantity %></span>
    <span class="quantity"><%= item.current_quantity %></span>
  </td>
</tr>

app/views/items/_items_form.html.erb
<div id="item_<%= index %>">
<% fields_for "items[#{index}]", item do |f| %>
  <p>
    <%= f.text_field :name %>
    <%= link_to 'remove', :url => { :action => 'remove_item', :index => index } %>
  </p>
<% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Needed quantity</th>
    <th>Current quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= item.needed_quantity %></td>
    <td><%= item.current_quantity %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Event id:</b>
  <%= @item.event_id %>
</p>

<p>
  <b>Needed quantity:</b>
  <%= @item.needed_quantity %>
</p>

<p>
  <b>Current quantity:</b>
  <%= @item.current_quantity %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Camilona :: <%= @title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "libs/require-min", :'data-main' => @main_app %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="wrapper container">
    
<%= if(controller.action_name != 'home' && controller.action_name != 'create') then render 'header' end %>

<%= yield %>

<%= if(controller.action_name != 'home' && controller.action_name != 'create') then render 'footer' end %>

</div>
</body>
</html>